### ISSUE TITLE
Implement following a user function

### ISSUE THREAD

**Issue by alecadub** [domludera/SOEN341UA4#10]
User should be able to click on a button, and follow that user. 

The user that has been followed will then see his new follower, and his number of followers increase by one.

**Comment by AAAnndrew** [comment]
Also, the User should be able to click on the same button, and unfollow that user.

the user that has been unfollowed will then see that number of followers is decreased by one.

**Comment by alecadub** [comment]
I added the milestone and refactored the labels for this user story. After meeting with the customer, this features should be implemented at the end of sprint 3

**Comment by alecadub** [comment]
This issue is a sub user story of #18 Implementing user profile. Once the profile is done, a user can check out a new user profile and follow that user.

**Comment by alecadub** [comment]
Fixed with merge of pull request #34
