### ISSUE TITLE
Implement posting tweets

### ISSUE THREAD

**Issue by John-Estrada** [domludera/SOEN341UA4#2]
- [x] Text box

- [x] Submit button

- [x] Store tweet in database (JSON file for now)

**Comment by NavRez** [comment]
I apologize, I accidentally clicked on your story and it caused me to "edit" when there's was nothing substantial done.

**Comment by alecadub** [comment]
I added the milestone. After meeting with the customer, this features should be implemented at the end of sprint 2.

**Comment by alecadub** [comment]
Issue was fixed with the merge of the pull request #16 Prototype
