### ISSUE TITLE
Implementing logout function

### ISSUE THREAD

**Issue by BaselKal** [domludera/SOEN341UA4#7]
Logout button that will log the user out of the database

**Comment by alecadub** [comment]
I added the milestone. After meeting with the customer, this features should be implemented at the end of sprint 2.

**Comment by alecadub** [comment]
This issue is pushed to sprint 4, as it isn't required by the customer to complete for sprint 3!

**Comment by alecadub** [comment]
This isn't a requirement, but would be nice to add to our project ! A user should be prompt to log in if he's not connected.
